sudo: false
language: java
#cache:
#  directories:
#  - "$HOME/.cache"
#deploy:
#  provider: script
#  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -Possrh deploy"
#  skip_cleanup: true
#  on:
#    tags: true

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)